"""create initial tables

Revision ID: 587b6f7fb883
Revises: 
Create Date: 2025-09-07 11:34:31.770949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587b6f7fb883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('posts',
                  sa.Column('id', sa.String(length=26), nullable=False),
                  sa.Column('title', sa.String(), nullable=False),
                  sa.Column('content', sa.String(), nullable=False),
                  sa.Column('published', sa.Boolean(),
                            server_default='TRUE', nullable=False),
                  sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                            server_default=sa.text('now()'), nullable=False),
                  sa.PrimaryKeyConstraint('id')
                  )
  op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_posts_id'), table_name='posts')
  op.drop_table('posts')
  # ### end Alembic commands ###
